use crate::app_config::{AppConfig, Locale, PathsConfig, Theme, UiConfig};
use crate::dto::{
    ActiveListLoadDto, ApplyModListDto, ApplyModListRequest, CatalogSnapshotDto, CleanModsRequest,
    CommandError, CommandErrorCode, ConfiguredDirectoryKind, CreateModListRequest,
    DeleteModListRequest, DependencyDto, DependencyGraphDto, DiagnosticCodeDto, DiagnosticDto,
    DiagnosticLocationDto, DisplayAliasDto, DuplicatePackageIdDto, EdgeDto, EdgeKindDto,
    EdgeSourceDto, ExportGameConfigBackupDto, ExportGameConfigBackupRequest,
    ExportLibrarySettingsFileDto, ExportLibrarySettingsFileRequest, ExportModListFileDto,
    ExportModListFileRequest, GameConfigBackupDto, GameConfigBackupMetaDto,
    ImportGameConfigBackupDto, ImportGameConfigBackupRequest, ImportLibrarySettingsFileRequest,
    ImportModListFileRequest, IncompatibilityDto, LibraryDto, LibrarySettingsDto,
    LibrarySettingsFileDto, LoadModFolderSizeRequest, LoadModPreviewRequest, LoadPlayerLogRequest,
    LogEntryDto, LogLevelDto, LogSourceDto, ModCatalogDto, ModCleanupCandidateDto,
    ModCleanupKindDto, ModCleanupPreviewDto, ModCleanupPreviewRequest, ModCleanupReasonDto,
    ModCleanupResultDto, ModCleanupSkippedDto, ModFolderSizeDto, ModIdentityDto, ModListDto,
    ModListEntryDto, ModListFileDto, ModListGroupChildDto, ModListIndexDto, ModListSummaryDto,
    ModMetadataDto, ModPreviewDto, ModTagBindingDto, ModsConfigDto, OpenConfiguredDirectoryRequest,
    OpenModFolderRequest, OpenSteamWorkshopPageRequest, PlayerLogDto, ReadSaveModIdsDto,
    ReadSaveModIdsRequest, RimrFileKind, RulesDto, SaveAppConfigRequest,
    SaveLibrarySettingsRequest, SaveModListRequest, SetCurrentModListRequest, SeverityDto,
    SourceKindDto, SteamWorkshopLogDto, SteamWorkshopLogEntryDto, SteamWorkshopOpenTarget,
    TagDefDto, ValidateActiveOrderRequest, ValidateOrderDto, ValidationReportDto,
};
use crate::paths::{DetectedPaths, PathDetectionWarning, Platform};
use ts_rs::{Config, TS};

pub fn generate_typescript() -> String {
    let cfg = Config::default();
    let mut out = String::from(
        "// This file is generated by `cargo run -p xtask -- export-bindings`.\n// Do not edit by hand.\n\n",
    );
    out.push_str("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n");
    push::<AppConfig>(&cfg, &mut out);
    push::<PathsConfig>(&cfg, &mut out);
    push::<UiConfig>(&cfg, &mut out);
    push::<Theme>(&cfg, &mut out);
    push::<Locale>(&cfg, &mut out);
    push::<DetectedPaths>(&cfg, &mut out);
    push::<PathDetectionWarning>(&cfg, &mut out);
    push::<Platform>(&cfg, &mut out);
    push::<CommandError>(&cfg, &mut out);
    push::<CommandErrorCode>(&cfg, &mut out);
    push::<SaveAppConfigRequest>(&cfg, &mut out);
    push::<CatalogSnapshotDto>(&cfg, &mut out);
    push::<ModCatalogDto>(&cfg, &mut out);
    push::<DuplicatePackageIdDto>(&cfg, &mut out);
    push::<ModMetadataDto>(&cfg, &mut out);
    push::<LoadModPreviewRequest>(&cfg, &mut out);
    push::<ModPreviewDto>(&cfg, &mut out);
    push::<LoadModFolderSizeRequest>(&cfg, &mut out);
    push::<ModFolderSizeDto>(&cfg, &mut out);
    push::<ModCleanupKindDto>(&cfg, &mut out);
    push::<ModCleanupReasonDto>(&cfg, &mut out);
    push::<ModCleanupCandidateDto>(&cfg, &mut out);
    push::<ModCleanupPreviewRequest>(&cfg, &mut out);
    push::<ModCleanupPreviewDto>(&cfg, &mut out);
    push::<CleanModsRequest>(&cfg, &mut out);
    push::<ModCleanupSkippedDto>(&cfg, &mut out);
    push::<ModCleanupResultDto>(&cfg, &mut out);
    push::<OpenModFolderRequest>(&cfg, &mut out);
    push::<OpenConfiguredDirectoryRequest>(&cfg, &mut out);
    push::<ConfiguredDirectoryKind>(&cfg, &mut out);
    push::<OpenSteamWorkshopPageRequest>(&cfg, &mut out);
    push::<SteamWorkshopOpenTarget>(&cfg, &mut out);
    push::<SteamWorkshopLogDto>(&cfg, &mut out);
    push::<SteamWorkshopLogEntryDto>(&cfg, &mut out);
    push::<LogSourceDto>(&cfg, &mut out);
    push::<LogLevelDto>(&cfg, &mut out);
    push::<LogEntryDto>(&cfg, &mut out);
    push::<LoadPlayerLogRequest>(&cfg, &mut out);
    push::<PlayerLogDto>(&cfg, &mut out);
    push::<RulesDto>(&cfg, &mut out);
    push::<DependencyDto>(&cfg, &mut out);
    push::<SourceKindDto>(&cfg, &mut out);
    push::<SeverityDto>(&cfg, &mut out);
    push::<DiagnosticCodeDto>(&cfg, &mut out);
    push::<DiagnosticLocationDto>(&cfg, &mut out);
    push::<DiagnosticDto>(&cfg, &mut out);
    push::<ActiveListLoadDto>(&cfg, &mut out);
    push::<ModsConfigDto>(&cfg, &mut out);
    push::<ValidateActiveOrderRequest>(&cfg, &mut out);
    push::<ValidateOrderDto>(&cfg, &mut out);
    push::<ValidationReportDto>(&cfg, &mut out);
    push::<DependencyGraphDto>(&cfg, &mut out);
    push::<EdgeDto>(&cfg, &mut out);
    push::<EdgeKindDto>(&cfg, &mut out);
    push::<EdgeSourceDto>(&cfg, &mut out);
    push::<IncompatibilityDto>(&cfg, &mut out);
    push::<ModIdentityDto>(&cfg, &mut out);
    push::<DisplayAliasDto>(&cfg, &mut out);
    push::<TagDefDto>(&cfg, &mut out);
    push::<ModTagBindingDto>(&cfg, &mut out);
    push::<LibrarySettingsDto>(&cfg, &mut out);
    push::<RimrFileKind>(&cfg, &mut out);
    push::<ModListGroupChildDto>(&cfg, &mut out);
    push::<ModListEntryDto>(&cfg, &mut out);
    push::<ModListDto>(&cfg, &mut out);
    push::<ModListSummaryDto>(&cfg, &mut out);
    push::<ModListIndexDto>(&cfg, &mut out);
    push::<LibraryDto>(&cfg, &mut out);
    push::<SaveLibrarySettingsRequest>(&cfg, &mut out);
    push::<CreateModListRequest>(&cfg, &mut out);
    push::<SaveModListRequest>(&cfg, &mut out);
    push::<DeleteModListRequest>(&cfg, &mut out);
    push::<SetCurrentModListRequest>(&cfg, &mut out);
    push::<ApplyModListRequest>(&cfg, &mut out);
    push::<ApplyModListDto>(&cfg, &mut out);
    push::<ModListFileDto>(&cfg, &mut out);
    push::<LibrarySettingsFileDto>(&cfg, &mut out);
    push::<ExportModListFileRequest>(&cfg, &mut out);
    push::<ExportModListFileDto>(&cfg, &mut out);
    push::<ImportModListFileRequest>(&cfg, &mut out);
    push::<ExportLibrarySettingsFileRequest>(&cfg, &mut out);
    push::<ExportLibrarySettingsFileDto>(&cfg, &mut out);
    push::<ImportLibrarySettingsFileRequest>(&cfg, &mut out);
    push::<GameConfigBackupMetaDto>(&cfg, &mut out);
    push::<GameConfigBackupDto>(&cfg, &mut out);
    push::<ExportGameConfigBackupRequest>(&cfg, &mut out);
    push::<ExportGameConfigBackupDto>(&cfg, &mut out);
    push::<ImportGameConfigBackupRequest>(&cfg, &mut out);
    push::<ImportGameConfigBackupDto>(&cfg, &mut out);
    push::<ReadSaveModIdsRequest>(&cfg, &mut out);
    push::<ReadSaveModIdsDto>(&cfg, &mut out);
    out
}

fn push<T: TS + 'static>(cfg: &Config, out: &mut String) {
    if let Some(docs) = T::docs() {
        out.push_str(&docs);
    }
    out.push_str("export ");
    out.push_str(&T::decl(cfg));
    out.push_str("\n\n");
}
